### ISSUE TITLE
[Feature Request] Multi-monitor workspace

### ISSUE THREAD

**Issue by jsaxx** [lars-berger/glaze-wm#1012]
### Describe the problem/motivation

When working with multiple monitors, I would like to have the option to have a workspace span multiple monitors.
I basically would like to see the same behaviour of a single monitor setup (where changes the whole view), to a multi monitor setup.

### Describe the solution you'd like

My setup looks like this:

```
workspaces:
  - name: '1a'
    bind_to_monitor: 0
    keep_alive: true
  - name: '1b'
    bind_to_monitor: 1
    keep_alive: true
  - name: '2a'
    bind_to_monitor: 0
    keep_alive: true
  - name: '2b'
    bind_to_monitor: 1
    keep_alive: true
  - name: '3a'
    bind_to_monitor: 0
    keep_alive: true
  - name: '3b'
    bind_to_monitor: 1
    keep_alive: true
```

Right now I have two small script that handle this in a hacky way: by focusing/un-focusing the opposite monitor.
e.g. I am looking at workspaces 1a and 1b on the respective monitors, with focus on 1b. If I wanna go to 2b, I will focus 2a, and back to 2b, moving both halves of workspace 2 in sequence.

Naturally this is not ideal as it clunks up the switching process, plus this is not handling the situation were a link to an app is launched and only one "half" of the workspace, where the target app is opened, gets switched.

Quickest way to "solve" this partially, would be exposing some kind of command that lets the user display/hide workspaces without moving the focus.
