### ISSUE TITLE
[Bug] PotPlayer popup windows flash constantly and cant right click

### ISSUE THREAD

**Issue by Bluecakes** [lars-berger/glaze-wm#1076]
### Describe the bug

**Info**
When using PotPlayer with GlazeWM, the main player works as expected but popup windows such as "Add Bookmark" and "File Information" constantly flicker and are difficult to close, requiring multiple clicks on the X to actually close the dialog.

Also, right clicking inside PotPlayer with GlazeWM running immediately flickers and closes, preventing the use of the context menu.

**Troubleshooting**
Using WindowSpy from AutoHotkey, i am able to see the class and exe that i can put into the GlazeWM config

```yaml
  - commands: ['ignore']
    match:
      # The right click menu is a part of PotPlayer so i've ignore the main window
      - window_class: { equals: 'PotPlayer64' }
        window_process: { equals: 'PotPlayerMini64' }
      # The preferences window and other windows like "Add Bookmarks" show up as #32770
      - window_class: { equals: '#32770'}
        window_process: { equals: 'PotPlayerMini64' }
```

After reloading the config and even relaunching GlazeWM entirely, the right click menu and windows like preferences continue to flicker and are unusable.

**OS**
Windows 10 Pro 22H2 19045.5371

Autohotkey screenshot
![Image](https://github.com/user-attachments/assets/8749feb1-e95f-455c-97c9-c36338a5fcec)

### Reproduction

1. Install GlazeWM
2. Install PotPlayer
3. Open PotPlayer
4. Right click inside PotPlayer
5. Press F5 to open the Preferences window

### Stack trace or error logs (if applicable)

```shell

```

### Version number

GlazeWM v3.8.1
