### ISSUE TITLE
[Bug] `wm-disable-binding-mode` does not run after `focus --workspace`

### ISSUE THREAD

**Issue by akinevz2** [lars-berger/glaze-wm#1117]
### Describe the bug

I have a keybinding mode called 'workspace' where a keybinding should switch to a different workspace, and disable the binding mode. This behaviour only works if switching to an inactive tag, i.e: not one being shown on any screen.

Switching to a workspace that is on another screen but not being shown works, but the binding mode does not get disabled. Hitting the same keybinding again subsequently does disable the mode.

I have trimmed my configuration to `testing.yaml` as seen below which exhibits expected behaviour:
```yaml
binding_modes:
  - name: 'workspace'
    keybindings:
      - commands: ['focus --workspace 1', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+1', '1']
      - commands: ['focus --workspace 2', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+2', '2']
      - commands: ['focus --workspace 3', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+3', '3']
keybindings:
  - commands: ['wm-enable-binding-mode --name workspace']
    bindings: ['alt+w']
```

### Reproduction

The below configuration produces the unintended behavior. I can attach additional verbose logs if necessary.

```yaml
general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application.
  # Example: The below command launches Zebar.
  # startup_commands: []
  # We can optionally enable zebar

  # NOTE: I have configured zebar to startup in quiet mode to simplify logging
  startup_commands: ['shell-exec zebar startup -q']

  # Commands to run just before the WM is shutdown.
  # shutdown_commands: []
  # Example: The below command kills Zebar.
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: 'window_focus'

  # How windows should be hidden when switching workspaces.
  # - 'cloak': Recommended. Hides windows with no animation.
  # - 'hide': Legacy method (v3.5 and earlier) that has a brief animation,
  # but has stability issues with some apps.
  hide_method: 'cloak'

  # Affects which windows get shown in the native Windows taskbar. Has no
  # effect if `hide_method: 'hide'`.
  # - 'true': Show all windows (regardless of workspace).
  # - 'false': Only show windows from the currently shown workspaces.
  show_all_in_taskbar: true

gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: true

  # Gap between adjacent windows.
  inner_gap: '5px'

  # Gap between windows and the screen edge.
  outer_gap:
    top: '50px'
    right: '10px'
    bottom: '10px'
    left: '10px'

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: '#0000FF'

    # Remove the title bar from the window's frame. Note that this can
    # cause rendering issues for some applications.
    hide_title_bar:
      enabled: false

    # Change the corner style of the window's frame.
    # ** Exclusive to Windows 11 due to API limitations.
    corner_style:
      enabled: true
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: 'rounded'

    # Change the transparency of the window.
    transparency:
      enabled: false
      # Can be something like '95%' or '0.95' for slightly transparent windows.
      # '0' or '0%' is fully transparent (and, by consequence, unfocusable).
      opacity: '95%'

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: true
      color: '#a1a1a1'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: 'square'
    transparency:
      enabled: false
      opacity: '0%'

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: 'floating'

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: true

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: '1'
    display_name: "work"
  - name: '2'
    display_name: "browser"
  - name: '3'
    display_name: "gaming"
  - name: '4'
  - name: '5'
  - name: '6'
  - name: '7'
  - name: '8'
  - name: '9'

window_rules:
  # - commands: ['move --workspace 3', 'wm-enable-binding-mode --name gaming']
  #   match:
  #     - window_title: { equals: 'Battle.net' }

  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }
      - window_process: { equals: 'EXCEL' }
        window_class: { not_regex: 'XLMAIN' }
      - window_process: { equals: 'WINWORD' }
        window_class: { not_regex: 'OpusApp' }
      - window_process: { equals: 'POWERPNT' }
        window_class: { not_regex: 'PPTFrameClass' }

binding_modes:
  # NOTE: the below added binding mode might be causing the issue
  - name: 'gaming'
    keybindings:
      - commands: ['focus --workspace 3']
        bindings: ['alt+space']
      - commands: ['wm-disable-binding-mode --name gaming', 'focus --prev-active-workspace']
        bindings: ['escape', 'enter', 'alt+x']

  - name: 'resize'
  # When enabled, the focused window can be resized via arrow keys or HJKL.
    keybindings:
      # Press enter/escape to return to default keybindings.
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter', 'alt+r']
      # Change focus to a workspace defined in `workspaces` config.
      - commands: ['resize --width -2%']
        bindings: ['h']
      - commands: ['resize --width +2%']
        bindings: ['l']
      - commands: ['resize --height +2%']
        bindings: ['k']
      - commands: ['resize --height -2%']
        bindings: ['j']
  - name: 'workspace'
    # NOTE: BUT the unintended behavior happens within this mode
    keybindings:
      # Press enter/escape to return to default keybindings.
      - commands: ['wm-disable-binding-mode --name workspace']
        bindings: ['escape', 'alt+w']
      # Focus the workspace that last had focus and return exit workspace mode
      - commands: ['focus --recent-workspace','wm-disable-binding-mode --name workspace']
        bindings: ['alt+x']
      - commands: ['shell-exec code %userprofile%/.glzr/glazewm/config.yaml', 'wm-disable-binding-mode --name workspace']
        bindings: ['c']
      # Change focus to a workspace defined in `workspaces` config.
      - commands: ['focus --workspace 1', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+1', '1']
      - commands: ['focus --workspace 2', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+2', '2']
      - commands: ['focus --workspace 3', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+3', '3']
      - commands: ['focus --workspace 4', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+4', '4']
      - commands: ['focus --workspace 5', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+5', '5']
      - commands: ['focus --workspace 6', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+6', '6']
      - commands: ['focus --workspace 7', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+7', '7']
      - commands: ['focus --workspace 8', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+8', '8']
      - commands: ['focus --workspace 9', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+9', '9']
      # Focus the next/previous active workspace defined in `workspaces` config.
      - commands: ['focus --next-active-workspace']
        bindings: ['alt+ctrl+h']
      - commands: ['focus --prev-active-workspace']
        bindings: ['alt+ctrl+l']
      - commands: ['focus --next-workspace']
        bindings: ['alt+ctrl+k']
      - commands: ['focus --prev-workspace']
        bindings: ['alt+ctrl+j']

      # Move the focused window's parent workspace to a monitor in a given
      # direction.
      - commands: ['move-workspace --direction left', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+shift+h']
      - commands: ['move-workspace --direction right', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+shift+l']
      - commands: ['move-workspace --direction up', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+shift+k']
      - commands: ['move-workspace --direction down', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+shift+j']

      # Move focused window to a workspace defined in `workspaces` config.
      - commands: ['move --workspace 1', 'focus --workspace 1', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+ctrl+1']
      - commands: ['move --workspace 2', 'focus --workspace 2', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+ctrl+2']
      - commands: ['move --workspace 3', 'focus --workspace 3', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+ctrl+3']
      - commands: ['move --workspace 4', 'focus --workspace 4', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+ctrl+4']
      - commands: ['move --workspace 5', 'focus --workspace 5', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+ctrl+5']
      - commands: ['move --workspace 6', 'focus --workspace 6', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+ctrl+6']
      - commands: ['move --workspace 7', 'focus --workspace 7', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+ctrl+7']
      - commands: ['move --workspace 8', 'focus --workspace 8', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+ctrl+8']
      - commands: ['move --workspace 9', 'focus --workspace 9', 'wm-disable-binding-mode --name workspace']
        bindings: ['alt+ctrl+9']

keybindings:
  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['alt+h']
  - commands: ['focus --direction right']
    bindings: ['alt+l']
  - commands: ['focus --direction up']
    bindings: ['alt+k']
  - commands: ['focus --direction down']
    bindings: ['alt+j']

  # Move focused window in a given direction.
  - commands: ['move --direction left']
    bindings: ['alt+shift+h', 'alt+shift+left']
  - commands: ['move --direction right']
    bindings: ['alt+shift+l', 'alt+shift+right']
  - commands: ['move --direction up']
    bindings: ['alt+shift+k', 'alt+shift+up']
  - commands: ['move --direction down']
    bindings: ['alt+shift+j', 'alt+shift+down']

  # Resize focused window by a percentage or pixel amount.
  - commands: ['resize --width -2%']
    bindings: ['alt+ctrl+h']
  - commands: ['resize --width +2%']
    bindings: ['alt+ctrl+l']
  - commands: ['resize --height +2%']
    bindings: ['alt+ctrl+k']
  - commands: ['resize --height -2%']
    bindings: ['alt+ctrl+j']

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ['wm-enable-binding-mode --name resize']
    bindings: ['alt+r']

  - commands: ['wm-enable-binding-mode --name workspace']
    bindings: ['alt+w']

  # Disables window management and all other keybindings until alt+x
  # is pressed again.
  - commands: ['wm-toggle-pause']
    bindings: ['alt+x']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['alt+r']

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ['wm-cycle-focus']
    bindings: ['alt+space']

  # Change the focused window to be floating.
  - commands: ['toggle-floating --centered=true']
    bindings: ['alt+f']

  # Change the focused window to be floating.
  - commands: ['set-tiling']
    bindings: ['alt+a']

  # Change the focused window to be tiling.
  - commands: ['toggle-tiling']
    bindings: ['alt+ctrl+space']

  # Change the focused window to be fullscreen.
  - commands: ['toggle-fullscreen']
    bindings: ['alt+ctrl+f', 'alt+m']

  # Minimize focused window.
  - commands: ['toggle-minimized']
    bindings: ['alt+d']

  # Close focused window.
  - commands: ['close']
    bindings: ['alt+ctrl+q']

  # Kill GlazeWM process safely.
  - commands: ['wm-exit']
    bindings: ['alt+ctrl+e']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['alt+ctrl+r']

  # Redraw all windows.
  - commands: ['wm-redraw']
    bindings: ['alt+shift+w']

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  - commands: ['shell-exec wt']
    bindings: ['alt+ctrl+enter']
```

### Stack trace or error logs (if applicable)

```shell

```

### Version number

3.9.1
