### ISSUE TITLE
Multi monitor workspace binding issue

### ISSUE THREAD

**Issue by nacho692** [lars-berger/glaze-wm#283]
I'm trying to bind specific workspaces to specific monitors, according to windows my left one is "2", the middle one is "1" and the right one is "3".
Clearly both 1, 2 and 3 should go to the middle monitor, but 1 and 2 is going to the left monitor and 3 to the right one.

```
workspaces:
  - name: "1"
    bind_to_monitor: 1

  - name: "2"
    bind_to_monitor: 1

  - name: "3"
    bind_to_monitor: 1

  - name: "4"
    bind_to_monitor: 2
    display_name: "4 Status"

  - name: "5"
    display_name: "5 TV"
    bind_to_monitor: 3

  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"
```

![image](https://user-images.githubusercontent.com/7344223/223886612-ebd94578-a938-4aa4-b0bd-4f5f0629c2dc.png)

Am I doing anything wrong?
