### ISSUE TITLE
[Feature Request] Zebar should shut down along with GlazeWM

### ISSUE THREAD

**Issue by AfzGit** [lars-berger/glaze-wm#650]
Only GlazeWM shuts down, leaving the Zebar on. Make them shutdown altogether when `alt+shift+e` is pressed.

**Comment by AfzGit** [comment]
While this gets fixed, you can manually shutdown zebar from the task manager.
![image](https://github.com/user-attachments/assets/069e84c8-8dcf-4136-8ae0-35c26eda393b)

**Comment by lars-berger** [comment]
There's also a system tray option to exit Zebar:

![image](https://github.com/user-attachments/assets/37143c4f-6003-4679-8aab-71f9c87bf51c)

Perhaps a `general.shutdownCommands` option should be added? It would also be possible currently to just chain a `shell-exec` command to the `alt+shift+e` keybinding to kill the Zebar process.

**Comment by ethanrutt** [comment]
I am dealing with this too. I added 
```
# Kill GlazeWM process safely.
- commands: ['shell-exec taskkill /IM "zebar.exe" /F', 'wm-exit']
  bindings: ['alt+shift+e']
 ```
 To my `config.yaml` for now which seems to work. This is not very robust though since if `zebar` isn't running then an error will be thrown.

**Comment by AfzGit** [comment]
> I am dealing with this too. I added
> 
> ```
> # Kill GlazeWM process safely.
> - commands: ['shell-exec taskkill /IM "zebar.exe" /F', 'wm-exit']
>   bindings: ['alt+shift+e']
> ```
> 
> To my `config.yaml` for now which seems to work. This is not very robust though since if `zebar` isn't running then an error will be thrown.

A good temporary fix.

**Comment by ParasiteDelta** [comment]
Another option, via Powershell:
```yaml
# Kill GlazeWM process safely.
  - commands: ['shell-exec powershell if (Get-Process -Name "zebar") { Stop-Process -Name "zebar" -Force }', 'wm-exit']
    bindings: ['alt+shift+e']
    ```
