### ISSUE TITLE
[Bug] Fullscreen videos, games and other apps via F11 don't work

### ISSUE THREAD

**Issue by perryhq** [lars-berger/glaze-wm#833]
### Describe the bug

When I set a window to fullscreen with the set-fullscreen command it works normally, but when I use the `F11` key, open a game in fullscreen or maximize a video the window just grows in size, still keeping the rounded corners and border decoration.
![image](https://github.com/user-attachments/assets/e28c263d-d533-4d2c-9d13-0c318c54c27b)
Notice how the window corners leave a small space showing the desktop and the border decoration still in view.

### Reproduction

```yaml
window_effects:
  focused_window:
    border:
      enabled: true
    fullscreen:
      maximized: true
      shown_on_top: false
```

### Version number

3.5.0
