### ISSUE TITLE
[Feature Request] Add support for per-workspace window effects

### ISSUE THREAD

**Issue by WillsonHaw** [lars-berger/glaze-wm#979]
### Describe the problem/motivation

I have a workflow where I use workspaces for different things (as most people probably do). I love the new transparency feature so I love most of my windows to be partially transparent so I can see my wallpaper. However, on one of my workspaces, I need to be able to see all windows at full opacity. Currently it doesn't seem like this can be done, as setting the opacity manually using `set-transparency --opacity 100%` will automatically get reset to the default value I've specified in `window_effects` once I've unfocused the window.

### Describe the solution you'd like

I would like to have a setting where window_effects could be overridden per-workspace. Perhaps something along the lines of

```yml
window_effects:
  focused_window:
    transparency:
      enabled: true
      opacity: "90%"

  # Visual effects to apply to non-focused windows.
  other_windows:
    transparency:
      enabled: true
      opacity: "70%"


workspaces:
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
    # override default window_effects for this workspace
    window_effects:
      focused_window:
        transparency:
          enabled: false
      other_windows:
        transparency:
          enabled: false
```

### Alternatives considered

Currently I can't use the transparency feature as is, without ability to set per-workspace effects or at the very least, being able to remember what opacity I've manually set a window to.

**Comment by bkomadina** [comment]
@WillsonHaw did the `set-transparency --opacity 0-100%` ever trigger an opacity change even briefly? if yes, could you please provide the code where you added that line?

I've tried the code below, move to workspace command moves Chrome to workspace 1 but the transparency doesn't change even when window_effects and focused_window transparency rules are just set to enabled without any further opacities set:
```
window_rules:
  - commands: ["move --workspace 1", "set-transparency --opacity 10%"]
    match:
      - window_process: { regex: "msedge|brave|chrome|firefox" }
```
